# Generated by Django 5.0.3 on 2024-03-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='image',
            new_name='cover_image',
        ),
        migrations.AddField(
            model_name='rooms',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='meal_images/'),
        ),
    ]
