# Generated by Django 5.0.3 on 2024-03-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_image_rooms_cover_image_rooms_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='meal_images/'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='meal_images/'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='meal_images/'),
        ),
    ]
