# Generated by Django 5.0.3 on 2024-03-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rooms_image2_rooms_image3_rooms_image4'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
