# Generated by Django 5.0.3 on 2024-03-20 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_rooms_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_reporting', models.DateField()),
                ('date_of_exit', models.DateField()),
                ('guests', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('mpesa', 'Mpesa'), ('pay_on_arrival', 'Pay on Arrival')], max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
