# Generated by Django 5.0.3 on 2024-03-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
