# Generated by Django 5.0.3 on 2024-03-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_order_meal_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
