# Generated by Django 5.0.3 on 2024-03-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedroom',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.IntegerField(),
        ),
    ]
