# Generated by Django 5.0.3 on 2024-03-20 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_meal_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedroom',
            old_name='price',
            new_name='amount_paid',
        ),
    ]
