# Generated by Django 5.0.3 on 2024-03-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_price_bookedroom_amount_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedroom',
            old_name='amount_paid',
            new_name='price',
        ),
    ]
