# Generated by Django 5.0.3 on 2024-04-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_amount_paid_bookedroom_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accommodation_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
