# Generated by Django 5.0.3 on 2024-04-01 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_income_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
